Handle EU datacenter tunnel shutdown
saucelabs/ci-sauce pull request #128
Opened 2022-07-29 16:06 UTC by alexh-sauce

The `openConnection()` function didn't take a dataCenter argument, so it never stored that information when the tunnel shuts down later.

This PR adds a new parameter to `openConnection()`, and adds a wrapper function to provide backwards compatibility.

2022-07-29 17:31 UTC, waggledans submitted a review, later dismissed

2022-08-01 08:39 UTC, krzysieksulejczak submitted a review, later dismissed

2022-08-01 13:01 UTC, valfirst requested changes

2022-08-02 00:31 UTC, alexh-sauce commented on src/main/java/com/saucelabs/ci/sauceconnect/SauceTunnelManager.java
> +    Process openConnection(String username, String apiKey, String dataCenter, int port, File sauceConnectJar, String options,PrintStream printStream, Boolean verboseLogging, String sauceConnectPath)
Fixed in 6a8aad4

2022-08-02 00:31 UTC, alexh-sauce commented on src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
> +    public Process openConnection(String username, String apiKey, String dataCenter, int port, File sauceConnectJar, String options,  PrintStream printStream, Boolean verboseLogging, String sauceConn
Fixed in 6a8aad4

2022-08-02 05:10 UTC, valfirst approved these changes

2022-08-02 16:30 UTC, sebv approved these changes

2022-08-02 16:45 UTC, merged