Use the new SauceREST APIs
saucelabs/ci-sauce pull request #158
Opened 2023-01-04 18:24 UTC by alexh-sauce

2023-01-18 23:58 UTC, amckenzie132 approved these changes
LGTM

2023-01-19 09:19 UTC, valfirst requested changes

2023-01-19 09:19 UTC, valfirst commented on src/main/java/com/saucelabs/ci/BrowserFactory.java
> +            if (seleniumName != null && seleniumName.equals(IEHTA)) {
```suggestion
            if (IEHTA.equals(seleniumName)) {
```

2023-01-19 09:19 UTC, valfirst commented on src/main/java/com/saucelabs/ci/BrowserFactory.java
> +            if (platform.device != null && platform.device != "") {
```suggestion
            if (platform.device != null && !platform.device.isEmpty()) {
```

2023-01-19 09:19 UTC, valfirst commented on src/main/java/com/saucelabs/ci/BrowserFactory.java
> +                browsers.add(browser);
```suggestion
                browsers.add(createDeviceBrowser(seleniumName, longName, longVersion, osName, device, deviceType, shortVersion, "portrait"));
                browsers.add(createDeviceBrowser(seleniumName, longName, longVersion, osName, device, deviceType, shortVersion, "landscape"));
```

2023-01-19 09:19 UTC, valfirst commented on src/main/java/com/saucelabs/ci/BrowserFactory.java
> +            browsers.add(browser);
```suggestion
            browsers.add(createBrowserBrowser(seleniumName, longName, "latest", osName, "latest"));
            browsers.add(createBrowserBrowser(seleniumName, longName, longVersion, osName, shortVersion));
```

2023-01-19 18:55 UTC, amckenzie132 approved these changes

2023-01-19 19:55 UTC, merged