Switch to sauceREST 2.1.1
saucelabs/ci-sauce pull request #200
Opened 2023-09-21 21:17 UTC by alexh-sauce

Use the new SauceREST APIs

2023-09-23 10:30 UTC, valfirst requested changes

2023-09-23 10:30 UTC, valfirst commented on src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
> +            scEndpoint = sauceRest.getSauceConnectEndpoint();
```suggestion
            sauceRest = setSauceRest(new SauceREST(username, apiKey, dataCenter));
```

2023-09-23 10:30 UTC, valfirst commented on src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
> +            if (tunnels.size() == 0) {
```suggestion
            if (tunnels.isEmpty()) {
```

2023-09-23 10:30 UTC, valfirst commented on src/main/java/com/saucelabs/ci/sauceconnect/AbstractSauceTunnelManager.java
> +                String tunnelId = tunnels.get(i);
```suggestion
            for (String tunnelId : tunnels) {
```

2023-09-23 10:30 UTC, valfirst commented on src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java
> +	ArrayList<String> empty = new ArrayList<String>();
```suggestion
	List<String> empty = new ArrayList<String>();
```

2023-09-23 10:30 UTC, valfirst commented on src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java
> +	ArrayList<String> empty = new ArrayList<String>();
```suggestion
	List<String> empty = new ArrayList<String>();
```

2023-09-23 10:30 UTC, valfirst commented on src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java
> +	ArrayList<String> empty = new ArrayList<String>();
```suggestion
	List<String> empty = new ArrayList<String>();
```

2023-09-23 10:30 UTC, valfirst commented on src/test/java/com/saucelabs/ci/sauceconnect/SauceConnectFourManagerTest.java
> +	ArrayList<String> active = new ArrayList<String>();
```suggestion
	List<String> active = new ArrayList<String>();
```

2023-09-26 08:21 UTC, valfirst approved these changes

2023-10-20 07:42 UTC, diemol approved these changes

2023-10-20 07:43 UTC, merged